const [APP_VERSION, APP_HOMEPAGE, APP_AUTHOR, APP_PLATFORM] = [
  process.env.APP_VERSION,
  process.env.APP_HOMEPAGE,
  process.env.APP_AUTHOR,
  process.env.APP_PLATFORM,
];

export { APP_AUTHOR, APP_HOMEPAGE, APP_VERSION, APP_PLATFORM };
