require 'json'

default_platform(:ios)

package = JSON.parse(File.read('../package.json'))

platform :ios do
  setup_ci
  desc "Build the production iOS app"
  lane :release do |options|
    match(type: "appstore", readonly: is_ci)
    increment_build_number(
      xcodeproj: "apps/mobile/ios/App/App.xcodeproj"
    )
    increment_version_number(
      version_number: package["version"],
      xcodeproj: "apps/mobile/ios/App/App.xcodeproj"
    )
    build_app(
        workspace: "apps/mobile/ios/App/App.xcworkspace",
        scheme: "App",
        output_directory: "apps/mobile/dist/ios",
        output_name: "lyricistant.ipa"
    )
    if options[:deploy]
      upload_to_app_store
    end
  end
end
