"""
Contains rules for testing using the Jest test runner.
"""

load("@npm//jest-cli:index.bzl", _jest_test = "jest_test")

def jest_test(name, srcs, deps, **kwargs):
    """A macro around the autogenerated jest_test rule

    Args:
      name: the name of the rule
      srcs: test file sources
      deps: dependencies needed to run the tests.
      **kwargs: Other arguments to pass directly to the jest_test rule.
    """

    templated_args = [
        "--no-cache",
        "--no-watchman",
        "--ci",
        "--colors",
    ]
    templated_args.extend(["--config", "$(rootpath //:jest.config.js)"])
    templated_args.extend(["--env", "$(rootpath //:default-jest-env.js)"])
    for src in srcs:
        templated_args.extend(["--runTestsByPath", "$(rootpaths %s)" % src])

    data = ["//:jest.config.js", "//:package.json", "//:default-jest-env.js", "@npm//identity-obj-proxy"] + srcs + deps
    _jest_test(
        name = name,
        data = data,
        templated_args = templated_args,
        **kwargs
    )
