name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 'Build and Check'
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel in-progress builds
        uses: styfle/cancel-workflow-action@148d9a848c6acaf90a3ec30bc5062f646f8a4163 # pin@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout the current branch.
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - name: Setup Node.js - 15.x.x
        uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f # pin@v2
        with:
          node-version: '>=15.10'
      - name: Setup virtual display
        run: Xvfb :99 &
      - name: Install Gulp
        run: npm install -g gulp@4.0.2
      - name: Install dependencies
        run: npm ci
      - name: Run all tests
        run: gulp testAll --max-old-space-size=8192
        env:
          DISPLAY: ':99'
      - name: Upload build artifacts
        if: failure()
        uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # pin@v2
        with:
          path: |
            apps/**/dist/
            dist/
      - name: Check for Lint issues.
        run: npm run lint
