name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: 'Build and Check'
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel in-progress builds
        uses: styfle/cancel-workflow-action@148d9a848c6acaf90a3ec30bc5062f646f8a4163 # pin@0.5.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout the current branch.
        uses: actions/checkout@f1d3225b5376a0791fdee5a0e8eac5289355e43a # pin@v2
      - name: Setup Node.js - 15.x.x
        uses: actions/setup-node@7984c00a6eb7ec35a15dd83fd6d4f88c67421da3 # pin@v1
        with:
          node-version: '>=15.10'
      - name: Setup virtual display
        run: Xvfb :99 &
      - name: Install Gulp
        run: npm install -g gulp@4.0.2
      - name: Install dependencies
        run: npm ci
      - name: Run all tests
        run: gulp testAll
        env:
          DISPLAY: ':99'
      - name: Check for Lint issues.
        run: npm run lint
