name: 'Nightly Releases'
'on':
  push:
    branches:
      - 'main'
jobs:
  cancelCurrentRuns:
    name: 'Cancel in-progress Workflow runs'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Cancel in-progress Workflow runs'
        uses: 'styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5'
        with:
          access_token: '${{ secrets.GITHUB_TOKEN }}'
  deployWeb:
    name: 'Deploy Web to dev.lyricistant.app'
    runs-on: 'ubuntu-20.04'
    needs:
      - 'cancelCurrentRuns'
    steps:
      - name: 'Mask any potential PII'
        run: "echo \"::add-mask::${{ secrets.PHONE_NUMBER }}\"\necho \"::add-mask::${{ secrets.APPLE_ID }}\""
      - name: 'Checkout the current branch'
        uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8'
        with:
          fetch-depth: 0
      - name: 'Setup Node.js - 18'
        uses: 'actions/setup-node@8c91899e586c5b171469028077307d293428b516'
        with:
          node-version: '>=18'
          cache: 'npm'
      - uses: 'actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7'
        name: 'Cache Node Modules'
        with:
          path: '~/.npm'
          key: '${{ runner.os}}-node-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: '${{ runner.os }}-node-'
      - name: 'Install Gulp'
        run: 'npm install -g gulp@4.0.2'
      - name: 'Install Node modules'
        run: 'npm ci'
      - name: 'Build Web'
        run: 'gulp buildWeb --max-old-space-size=8192'
        env:
          NIGHTLY: true
      - name: 'Deploy Web'
        uses: 'peaceiris/actions-gh-pages@de7ea6f8efb354206b205ef54722213d99067935'
        with:
          personal_token: '${{ secrets.LYRICISTANT_TOKEN }}'
          publish_branch: 'gh-pages'
          publish_dir: 'apps/web/dist/production/'
          force_orphan: true
          cname: 'dev.lyricistant.app'
  buildIOSApp:
    name: 'Build iOS'
    runs-on: 'macos-12'
    steps:
      - name: 'Mask any potential PII'
        run: "echo \"::add-mask::${{ secrets.PHONE_NUMBER }}\"\necho \"::add-mask::${{ secrets.APPLE_ID }}\""
      - name: 'Checkout the current branch'
        uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8'
        with:
          fetch-depth: 0
      - name: 'Setup Node.js - 18'
        uses: 'actions/setup-node@8c91899e586c5b171469028077307d293428b516'
        with:
          node-version: '>=18'
          cache: 'npm'
      - uses: 'actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7'
        name: 'Cache Node Modules'
        with:
          path: '~/.npm'
          key: '${{ runner.os}}-node-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: '${{ runner.os }}-node-'
      - name: 'Install Gulp'
        run: 'npm install -g gulp@4.0.2'
      - name: 'Setup Ruby'
        uses: 'ruby/setup-ruby@c7079efafd956afb5d823e8999c2506e1053aefa'
        with:
          bundler-cache: true
      - name: 'Install Fastlane'
        run: 'gem install bundler && bundle install'
      - name: 'Install Node modules'
        run: 'npm ci'
      - name: 'Create App Store Connect credentials'
        run: 'echo "${{ secrets.APP_STORE_CONNECT_KEY }}" | base64 --decode > apps/mobile/ios/authkey.p8'
      - name: 'Bundle Mobile'
        run: 'gulp bundleIOS --max-old-space-size=8192'
        env:
          NIGHTLY: true
      - name: 'Build iOS'
        run: 'bundle exec fastlane ios release'
        env:
          APP_STORE_KEY_ID: '${{ secrets.APP_STORE_KEY_ID }}'
          APP_STORE_ISSUER_ID: '${{ secrets.APP_STORE_ISSUER_ID }}'
          FIRST_NAME: 'Wardell'
          LAST_NAME: 'Bagby'
          PHONE: '${{ secrets.PHONE }}'
          EMAIL: '${{ secrets.APPLE_ID }}'
          MATCH_GIT_BASIC_AUTHORIZATION: '${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
      - name: 'Upload iOS app'
        uses: 'actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb'
        with:
          name: 'ios-app'
          path: 'apps/mobile/dist/ios/*.ipa'
    needs:
      - 'cancelCurrentRuns'
  buildAndroidApp:
    name: 'Build Android'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Mask any potential PII'
        run: "echo \"::add-mask::${{ secrets.PHONE_NUMBER }}\"\necho \"::add-mask::${{ secrets.APPLE_ID }}\""
      - name: 'Checkout the current branch'
        uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8'
        with:
          fetch-depth: 0
      - name: 'Setup Node.js - 18'
        uses: 'actions/setup-node@8c91899e586c5b171469028077307d293428b516'
        with:
          node-version: '>=18'
          cache: 'npm'
      - uses: 'actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7'
        name: 'Cache Node Modules'
        with:
          path: '~/.npm'
          key: '${{ runner.os}}-node-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: '${{ runner.os }}-node-'
      - name: 'Install Gulp'
        run: 'npm install -g gulp@4.0.2'
      - name: 'Setup Ruby'
        uses: 'ruby/setup-ruby@c7079efafd956afb5d823e8999c2506e1053aefa'
        with:
          bundler-cache: true
      - name: 'Install Fastlane'
        run: 'gem install bundler && bundle install'
      - name: 'Install Node modules'
        run: 'npm ci'
      - name: 'Populate keystore'
        run: 'echo "${{ secrets.KEYSTORE }}" | base64 --decode > apps/mobile/android/android.keystore'
      - name: 'Populate keystore properties'
        run: 'echo "${{ secrets.KEYSTORE_PROPERTIES }}" | base64 --decode > apps/mobile/android/keystore.properties'
      - name: 'Populate Play Store credentials'
        run: 'echo "${{ secrets.PLAY_STORE_CREDS }}" | base64 --decode > play-store-credentials.json'
      - name: 'Bundle Mobile'
        run: 'gulp bundleAndroid --max-old-space-size=8192'
        env:
          NIGHTLY: true
      - name: 'Build Android'
        run: 'bundle exec fastlane android release'
      - name: 'Upload Android app'
        uses: 'actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb'
        with:
          name: 'android-app'
          path: 'apps/mobile/dist/android/*.apk'
    needs:
      - 'cancelCurrentRuns'
  buildElectronApps:
    name: 'Build Electron Apps'
    runs-on: 'macos-12'
    steps:
      - name: 'Mask any potential PII'
        run: "echo \"::add-mask::${{ secrets.PHONE_NUMBER }}\"\necho \"::add-mask::${{ secrets.APPLE_ID }}\""
      - name: 'Checkout the current branch'
        uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8'
        with:
          fetch-depth: 0
      - name: 'Setup Node.js - 18'
        uses: 'actions/setup-node@8c91899e586c5b171469028077307d293428b516'
        with:
          node-version: '>=18'
          cache: 'npm'
      - uses: 'actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7'
        name: 'Cache Node Modules'
        with:
          path: '~/.npm'
          key: '${{ runner.os}}-node-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: '${{ runner.os }}-node-'
      - name: 'Install Gulp'
        run: 'npm install -g gulp@4.0.2'
      - name: 'Install Node modules'
        run: 'npm ci'
      - name: 'Build Electron apps'
        uses: 'nick-invision/retry@3e91a01664abd3c5cd539100d10d33b9c5b68482'
        env:
          CSC_LINK: '${{ secrets.MACOS_CERT }}'
          CSC_KEY_PASSWORD: '${{ secrets.MACOS_CERT_PASSWORD }}'
          APPLE_ID: '${{ secrets.APPLE_ID }}'
          APPLE_ID_PASSWORD: '${{ secrets.APPLE_ID_PASSWORD }}'
          NIGHTLY: true
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: 'gulp buildAllElectronApps --max-old-space-size=8192'
      - name: 'Upload Electron apps'
        uses: 'actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb'
        with:
          name: 'electron-apps'
          path: 'apps/electron/dist/production/app/*.*'
    needs:
      - 'cancelCurrentRuns'
  createGithubRelease:
    name: 'Create Github Nightly Release'
    runs-on: 'ubuntu-20.04'
    needs:
      - 'buildIOSApp'
      - 'buildElectronApps'
      - 'buildAndroidApp'
    steps:
      - name: 'Mask any potential PII'
        run: "echo \"::add-mask::${{ secrets.PHONE_NUMBER }}\"\necho \"::add-mask::${{ secrets.APPLE_ID }}\""
      - name: 'Checkout the current branch'
        uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8'
        with:
          fetch-depth: 0
      - name: 'Setup Node.js - 18'
        uses: 'actions/setup-node@8c91899e586c5b171469028077307d293428b516'
        with:
          node-version: '>=18'
          cache: 'npm'
      - uses: 'actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7'
        name: 'Cache Node Modules'
        with:
          path: '~/.npm'
          key: '${{ runner.os}}-node-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: '${{ runner.os }}-node-'
      - name: 'Install Gulp'
        run: 'npm install -g gulp@4.0.2'
      - name: 'Install Node modules'
        run: 'npm ci'
      - name: 'Create Github release notes'
        run: './scripts/create_release_changelog.ts all release.txt unreleased'
      - name: 'Download iOS app'
        uses: 'actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7'
        with:
          name: 'ios-app'
          path: '/tmp/artifacts'
      - name: 'Download Electron apps'
        uses: 'actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7'
        with:
          name: 'electron-apps'
          path: '/tmp/artifacts'
      - name: 'Download Android app'
        uses: 'actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7'
        with:
          name: 'android-app'
          path: '/tmp/artifacts'
      - name: 'Delete current nightly tag and release'
        uses: 'dev-drprasad/delete-tag-and-release/@8cd619d00037e4aeb781909c9a6b03940507d0da'
        with:
          delete_release: true
          tag_name: 'latest'
          github_token: '${{ secrets.GITHUB_TOKEN }}'
      - name: 'Create Nightly Github release'
        uses: 'softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844'
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          body_path: 'release.txt'
          files: '/tmp/artifacts/*.*'
          name: 'Lyricistant - Nightly'
          tag_name: 'latest'
          prerelease: true
