name: 'Production Releases'
'on':
  push:
    tags:
      - 'v*'
jobs:
  uiTest:
    name: 'UI Tests'
    runs-on: 'ubuntu-22.04'
    steps:
      - name: 'Mask any potential PII'
        run: "echo \"::add-mask::${{ secrets.PHONE_NUMBER }}\"\necho \"::add-mask::${{ secrets.APPLE_ID }}\""
      - name: 'Checkout the current branch'
        uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8'
        with:
          fetch-depth: 0
      - name: 'Setup Node.js - 18'
        uses: 'actions/setup-node@8c91899e586c5b171469028077307d293428b516'
        with:
          node-version: '>=18'
          cache: 'npm'
      - uses: 'actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7'
        name: 'Cache Node Modules'
        with:
          path: '~/.npm'
          key: '${{ runner.os}}-node-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: '${{ runner.os }}-node-'
      - name: 'Install Gulp'
        run: 'npm install -g gulp@4.0.2'
      - name: 'Install Node modules'
        run: 'npm ci'
      - name: 'Set virtual display if Ubuntu'
        if: 'runner.os == ''Linux'''
        run: 'Xvfb :99 &'
      - name: 'Setup Playwright dependencies'
        run: 'sudo npx playwright install-deps'
      - name: 'Run UI tests'
        run: 'gulp uiTests --max-old-space-size=8192'
        env:
          DISPLAY: ':99'
      - name: 'Upload build artifacts if failed'
        if: 'failure()'
        uses: 'actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb'
        with:
          path: "apps/**/dist/\ndist/"
  unitTest:
    name: 'Unit Tests'
    runs-on: 'ubuntu-22.04'
    steps:
      - name: 'Mask any potential PII'
        run: "echo \"::add-mask::${{ secrets.PHONE_NUMBER }}\"\necho \"::add-mask::${{ secrets.APPLE_ID }}\""
      - name: 'Checkout the current branch'
        uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8'
        with:
          fetch-depth: 0
      - name: 'Setup Node.js - 18'
        uses: 'actions/setup-node@8c91899e586c5b171469028077307d293428b516'
        with:
          node-version: '>=18'
          cache: 'npm'
      - uses: 'actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7'
        name: 'Cache Node Modules'
        with:
          path: '~/.npm'
          key: '${{ runner.os}}-node-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: '${{ runner.os }}-node-'
      - name: 'Install Gulp'
        run: 'npm install -g gulp@4.0.2'
      - name: 'Install Node modules'
        run: 'npm ci'
      - name: 'Set virtual display if Ubuntu'
        if: 'runner.os == ''Linux'''
        run: 'Xvfb :99 &'
      - name: 'Setup Playwright dependencies'
        run: 'sudo npx playwright install-deps'
      - name: 'Run unit tests'
        run: 'gulp unitTests --max-old-space-size=8192'
  deployWeb:
    name: 'Deploy Web to lyricistant.app'
    runs-on: 'ubuntu-22.04'
    needs:
      - 'uiTest'
      - 'unitTest'
    if: '${{ contains(github.ref, ''web'') || endsWith(github.ref, ''0'') || endsWith(github.ref, ''1'') || endsWith(github.ref, ''2'') || endsWith(github.ref, ''3'') || endsWith(github.ref, ''4'') || endsWith(github.ref, ''5'') || endsWith(github.ref, ''6'') || endsWith(github.ref, ''7'') || endsWith(github.ref, ''8'') || endsWith(github.ref, ''9'') }}'
    steps:
      - name: 'Mask any potential PII'
        run: "echo \"::add-mask::${{ secrets.PHONE_NUMBER }}\"\necho \"::add-mask::${{ secrets.APPLE_ID }}\""
      - name: 'Checkout the current branch'
        uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8'
        with:
          fetch-depth: 0
      - name: 'Setup Node.js - 18'
        uses: 'actions/setup-node@8c91899e586c5b171469028077307d293428b516'
        with:
          node-version: '>=18'
          cache: 'npm'
      - uses: 'actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7'
        name: 'Cache Node Modules'
        with:
          path: '~/.npm'
          key: '${{ runner.os}}-node-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: '${{ runner.os }}-node-'
      - name: 'Install Gulp'
        run: 'npm install -g gulp@4.0.2'
      - name: 'Install Node modules'
        run: 'npm ci'
      - name: 'Build Web'
        run: 'gulp buildWeb --max-old-space-size=8192'
      - name: 'Deploy Web'
        uses: 'peaceiris/actions-gh-pages@de7ea6f8efb354206b205ef54722213d99067935'
        with:
          personal_token: '${{ secrets.LYRICISTANT_TOKEN }}'
          publish_branch: 'gh-pages'
          publish_dir: 'apps/web/dist/production/'
          force_orphan: true
          cname: 'lyricistant.app'
          external_repository: 'wardellbagby/lyricistant-website'
  buildIOSApp:
    name: 'Build iOS'
    runs-on: 'macos-13'
    steps:
      - name: 'Mask any potential PII'
        run: "echo \"::add-mask::${{ secrets.PHONE_NUMBER }}\"\necho \"::add-mask::${{ secrets.APPLE_ID }}\""
      - name: 'Checkout the current branch'
        uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8'
        with:
          fetch-depth: 0
      - name: 'Setup Node.js - 18'
        uses: 'actions/setup-node@8c91899e586c5b171469028077307d293428b516'
        with:
          node-version: '>=18'
          cache: 'npm'
      - uses: 'actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7'
        name: 'Cache Node Modules'
        with:
          path: '~/.npm'
          key: '${{ runner.os}}-node-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: '${{ runner.os }}-node-'
      - name: 'Install Gulp'
        run: 'npm install -g gulp@4.0.2'
      - name: 'Setup Ruby'
        uses: 'ruby/setup-ruby@c7079efafd956afb5d823e8999c2506e1053aefa'
        with:
          bundler-cache: true
      - name: 'Install Fastlane'
        run: 'gem install bundler && bundle install'
      - name: 'Install Node modules'
        run: 'npm ci'
      - name: 'Create App Store Connect credentials'
        run: 'echo "${{ secrets.APP_STORE_CONNECT_KEY }}" | base64 --decode > apps/mobile/ios/authkey.p8'
      - name: 'Bundle Mobile'
        run: 'gulp bundleIOS --max-old-space-size=8192'
        env:
          NIGHTLY: false
      - name: 'Create iOS release notes'
        run: './scripts/create_release_changelog.ts ios fastlane/metadata/ios/en-US/release_notes.txt'
      - name: 'Build iOS'
        run: 'bundle exec fastlane ios release deploy:true'
        env:
          APP_STORE_KEY_ID: '${{ secrets.APP_STORE_KEY_ID }}'
          APP_STORE_ISSUER_ID: '${{ secrets.APP_STORE_ISSUER_ID }}'
          FIRST_NAME: 'Wardell'
          LAST_NAME: 'Bagby'
          PHONE: '${{ secrets.PHONE }}'
          EMAIL: '${{ secrets.APPLE_ID }}'
          MATCH_GIT_BASIC_AUTHORIZATION: '${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
      - name: 'Upload iOS app'
        uses: 'actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb'
        with:
          name: 'ios-app'
          path: 'apps/mobile/dist/ios/*.ipa'
    needs:
      - 'uiTest'
      - 'unitTest'
    if: '${{ contains(github.ref, ''ios'') || endsWith(github.ref, ''0'') || endsWith(github.ref, ''1'') || endsWith(github.ref, ''2'') || endsWith(github.ref, ''3'') || endsWith(github.ref, ''4'') || endsWith(github.ref, ''5'') || endsWith(github.ref, ''6'') || endsWith(github.ref, ''7'') || endsWith(github.ref, ''8'') || endsWith(github.ref, ''9'') }}'
  buildAndroidApp:
    name: 'Build Android'
    runs-on: 'ubuntu-22.04'
    steps:
      - name: 'Mask any potential PII'
        run: "echo \"::add-mask::${{ secrets.PHONE_NUMBER }}\"\necho \"::add-mask::${{ secrets.APPLE_ID }}\""
      - name: 'Checkout the current branch'
        uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8'
        with:
          fetch-depth: 0
      - name: 'Setup Node.js - 18'
        uses: 'actions/setup-node@8c91899e586c5b171469028077307d293428b516'
        with:
          node-version: '>=18'
          cache: 'npm'
      - uses: 'actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7'
        name: 'Cache Node Modules'
        with:
          path: '~/.npm'
          key: '${{ runner.os}}-node-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: '${{ runner.os }}-node-'
      - name: 'Install Gulp'
        run: 'npm install -g gulp@4.0.2'
      - name: 'Setup Ruby'
        uses: 'ruby/setup-ruby@c7079efafd956afb5d823e8999c2506e1053aefa'
        with:
          bundler-cache: true
      - name: 'Install Fastlane'
        run: 'gem install bundler && bundle install'
      - name: 'Install Node modules'
        run: 'npm ci'
      - name: 'Populate keystore'
        run: 'echo "${{ secrets.KEYSTORE }}" | base64 --decode > apps/mobile/android/android.keystore'
      - name: 'Populate keystore properties'
        run: 'echo "${{ secrets.KEYSTORE_PROPERTIES }}" | base64 --decode > apps/mobile/android/keystore.properties'
      - name: 'Populate Play Store credentials'
        run: 'echo "${{ secrets.PLAY_STORE_CREDS }}" | base64 --decode > play-store-credentials.json'
      - name: 'Bundle Mobile'
        run: 'gulp bundleAndroid --max-old-space-size=8192'
        env:
          NIGHTLY: false
      - name: 'Create Android release notes'
        run: './scripts/create_release_changelog.ts android fastlane/metadata/android/en-US/changelogs/default.txt'
      - name: 'Build Android'
        run: 'bundle exec fastlane android release deploy:true'
      - name: 'Upload Android app'
        uses: 'actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb'
        with:
          name: 'android-app'
          path: 'apps/mobile/dist/android/*.apk'
    needs:
      - 'uiTest'
      - 'unitTest'
    if: '${{ contains(github.ref, ''android'') || endsWith(github.ref, ''0'') || endsWith(github.ref, ''1'') || endsWith(github.ref, ''2'') || endsWith(github.ref, ''3'') || endsWith(github.ref, ''4'') || endsWith(github.ref, ''5'') || endsWith(github.ref, ''6'') || endsWith(github.ref, ''7'') || endsWith(github.ref, ''8'') || endsWith(github.ref, ''9'') }}'
  buildElectronApps:
    name: 'Build Electron Apps'
    runs-on: 'macos-13'
    steps:
      - name: 'Mask any potential PII'
        run: "echo \"::add-mask::${{ secrets.PHONE_NUMBER }}\"\necho \"::add-mask::${{ secrets.APPLE_ID }}\""
      - name: 'Checkout the current branch'
        uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8'
        with:
          fetch-depth: 0
      - name: 'Setup Node.js - 18'
        uses: 'actions/setup-node@8c91899e586c5b171469028077307d293428b516'
        with:
          node-version: '>=18'
          cache: 'npm'
      - uses: 'actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7'
        name: 'Cache Node Modules'
        with:
          path: '~/.npm'
          key: '${{ runner.os}}-node-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: '${{ runner.os }}-node-'
      - name: 'Install Gulp'
        run: 'npm install -g gulp@4.0.2'
      - name: 'Install Node modules'
        run: 'npm ci'
      - name: 'Build Electron apps'
        uses: 'nick-invision/retry@3e91a01664abd3c5cd539100d10d33b9c5b68482'
        env:
          CSC_LINK: '${{ secrets.MACOS_CERT }}'
          CSC_KEY_PASSWORD: '${{ secrets.MACOS_CERT_PASSWORD }}'
          APPLE_ID: '${{ secrets.APPLE_ID }}'
          APPLE_ID_PASSWORD: '${{ secrets.APPLE_ID_PASSWORD }}'
          NIGHTLY: false
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: 'gulp buildAllElectronApps --max-old-space-size=8192'
      - name: 'Upload Electron apps'
        uses: 'actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb'
        with:
          name: 'electron-apps'
          path: 'apps/electron/dist/production/app/*.*'
    needs:
      - 'uiTest'
      - 'unitTest'
    if: '${{ contains(github.ref, ''electron'') || endsWith(github.ref, ''0'') || endsWith(github.ref, ''1'') || endsWith(github.ref, ''2'') || endsWith(github.ref, ''3'') || endsWith(github.ref, ''4'') || endsWith(github.ref, ''5'') || endsWith(github.ref, ''6'') || endsWith(github.ref, ''7'') || endsWith(github.ref, ''8'') || endsWith(github.ref, ''9'') }}'
  createGithubRelease:
    name: 'Create Github Release'
    runs-on: 'ubuntu-22.04'
    if: 'always()'
    needs:
      - 'buildIOSApp'
      - 'buildElectronApps'
      - 'buildAndroidApp'
    steps:
      - name: 'Mask any potential PII'
        run: "echo \"::add-mask::${{ secrets.PHONE_NUMBER }}\"\necho \"::add-mask::${{ secrets.APPLE_ID }}\""
      - name: 'Checkout the current branch'
        uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8'
        with:
          fetch-depth: 0
      - name: 'Setup Node.js - 18'
        uses: 'actions/setup-node@8c91899e586c5b171469028077307d293428b516'
        with:
          node-version: '>=18'
          cache: 'npm'
      - uses: 'actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7'
        name: 'Cache Node Modules'
        with:
          path: '~/.npm'
          key: '${{ runner.os}}-node-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: '${{ runner.os }}-node-'
      - name: 'Install Gulp'
        run: 'npm install -g gulp@4.0.2'
      - name: 'Install Node modules'
        run: 'npm ci'
      - name: 'Create Github release notes'
        run: './scripts/create_release_changelog.ts all release.txt'
      - name: 'Download iOS app'
        uses: 'actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7'
        with:
          name: 'ios-app'
          path: '/tmp/artifacts'
        if: 'needs.buildIOSApp.result == ''success'''
      - name: 'Download Electron apps'
        uses: 'actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7'
        with:
          name: 'electron-apps'
          path: '/tmp/artifacts'
        if: 'needs.buildElectronApps.result == ''success'''
      - name: 'Download Android app'
        uses: 'actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7'
        with:
          name: 'android-app'
          path: '/tmp/artifacts'
        if: 'needs.buildAndroidApp.result == ''success'''
      - name: 'Create Github release'
        uses: 'softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844'
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          body_path: 'release.txt'
          files: '/tmp/artifacts/*.*'
          prerelease: false
        if: '${{ needs.buildIOSApp.result == ''success'' || needs.buildElectronApps.result == ''success'' || needs.buildAndroidApp.result == ''success'' }}'
