name: 'Regenerate Pronunciations'
'on':
  push:
    branches:
      - 'main'
    paths:
      - 'tooling/additional_pronounciations.dict'
  schedule:
    - cron: '0 0 */14 * *'
  workflow_dispatch: {}
jobs:
  cancelCurrentRuns:
    name: 'Cancel in-progress Workflow runs'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Cancel in-progress Workflow runs'
        uses: 'styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5'
        with:
          access_token: '${{ secrets.GITHUB_TOKEN }}'
  generation:
    name: 'Generation'
    needs:
      - 'cancelCurrentRuns'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Checkout the current branch'
        uses: 'actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8'
        with:
          fetch-depth: 0
          token: '${{ secrets.LYRICISTANT_TOKEN }}'
      - name: 'Setup Node.js - 15.x.x'
        uses: 'actions/setup-node@8c91899e586c5b171469028077307d293428b516'
        with:
          node-version: '>=15.10'
          cache: 'npm'
      - uses: 'actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7'
        name: 'Cache Node Modules'
        with:
          path: '~/.npm'
          key: '${{ runner.os}}-node-${{ hashFiles(''**/package-lock.json'') }}'
          restore-keys: '${{ runner.os }}-node-'
      - name: 'Install Node modules'
        run: 'npm ci'
      - name: 'Setup Git author'
        run: 'git config --local user.name ''github-actions'' && git config --local user.email ''41898282+github-actions[bot]@users.noreply.github.com'''
      - name: 'Generate pronunciations'
        run: 'tooling/create_pronunciations.ts'
      - name: 'Create & push changes if there are any'
        run: 'git diff --quiet && git diff --staged --quiet || (git commit --no-verify --all -m "chore: update pronunciations" && git push --no-verify)'
