name: Production Releases
on:
  push:
    tags:
      - "v*"
jobs:
  assert-no-issues:
    name: "Assert no issues"
    runs-on: macos-latest
    steps:
      - name: Checkout the current branch.
        uses: actions/checkout@v2
      - name: Setup Node.js - 14.x.x
        uses: actions/setup-node@v1
        with:
          node-version: '>=14.15'
      - name: Install Bazelisk
        run: npm install -g @bazel/bazelisk@1.7.3
      - name: Run all tests
        run: bazel test --build_tests_only //...
      - name: Check for Lint issues.
        run: npm run lint
  deploy-web:
    name: "Deploy Web"
    runs-on: ubuntu-latest
    needs: cancel-deploys
    steps:
      - name: Checkout the current branch.
        uses: actions/checkout@v2
      - name: Setup Node.js - 14.x.x
        uses: actions/setup-node@v1
        with:
          node-version: '>=14.15'
      - name: Install Bazelisk
        run: npm install -g @bazel/bazelisk@1.7.3
      - name: Build Web.
        run: 'bazel build //apps/web:app --define=mode=release'
      - name: Unzip Web archive
        run: 'unzip dist/bin/apps/web/app.zip -d /tmp/web'
      - name: Deploy Web
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.LYRICISTANT_TOKEN }}
          external_repository: wardellbagby/lyricistant-website
          publish_branch: gh-pages
          publish_dir: '/tmp/web'
          force_orphan: true
          cname: lyricistant.app
  deploy-app:
    needs: assert-no-issues
    name: "Deploy App"
    runs-on: macos-latest
    steps:
      - name: Checkout the current branch.
        uses: actions/checkout@v2
      - name: Setup Node.js - 14.x.x
        uses: actions/setup-node@v1
        with:
          node-version: '>=14.15'
      - name: Install Bazelisk
        run: npm install -g @bazel/bazelisk@1.7.3
      - name: Build artifacts for all supported OSes.
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 20
          max_attempts: 3
          command: |
            bazel build //apps/electron:app --define=mode=release \
            --action_env=CSC_LINK=${{ secrets.MACOS_CERT }} --action_env=CSC_KEY_PASSWORD=${{ secrets.MACOS_CERT_PASSWORD }} \
            --action_env=APPLE_ID=${{ secrets.APPLE_ID }} --action_env=APPLE_ID_PASSWORD=${{ secrets.APPLE_ID_PASSWORD }}
      - name: "Deploy App"
        uses: "marvinpinto/action-automatic-releases@4e86dbc"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: dist/bin/apps/electron/app/*.*